export const messageValidator = {
  isEmail: 'Must be an email',
  notEmpty: 'Not empty this field',
  minLength: 'Must be at least 5 characters',
  isExistEmail: 'Email already exist',
  notMatch: "Password doesn't match",
  dateFormat: 'Date format not valid',
  default: 'Validate fail, try again',
  notFound: 'Email or password not correct',
  notLogin: 'You are not login',
  tokenNotValid: 'Token not valid, try again',
  notFoundToken: 'Not found tokens, try again',
  notVerified: 'User not verified',
  mustBeString: 'This field must be string',
  maxLengthBio: 'Maximum 200 characters',
  maxLengthURL: 'Maximum 100 characters',
  usernameExist: 'Username already exist',
  regexString: "Can't contain special characters",
  objectIdValid: 'This id is not ObjectId, try again',
  imageUpload: 'File type must be image',
  tweetParentId: 'Parent id must be ObjectId',
  nomalTweet: 'This is a tweet, parent_id must be null',
  reTweetContent: 'This is retweet, content must be empty',
  tweetHashTag: 'Hashtag not valid',
  tweetMetions: 'Menitons must be array ObjectId',
  tweetMedia: 'Media format not valid',
  tweetNotFound: 'Tweet not found, try again',
  tweetNotPublic: 'Tweet is not public for everyone',
  pageValidate: 'Must be number',
  notFoundMessage: 'Message you found not exist or removed'
} as const

export const messResponse = {
  loginSuccess: 'Login successful',
  registerSuccess: 'Register successful',
  logoutSuccess: 'Logout successful',
  notFoundUser: 'Not found user, try again',
  verified: 'This email already verified',
  verifyOK: 'Verify success',
  resendVerify: 'Resend email verify success',
  sendEmailReset: 'Send email reset password success',
  changePassword: 'Change password successful',
  tokensExpired: 'Token already expired',
  updatedProfile: 'Update profile successful!',
  getMyInfo: 'Get info ok!!',
  followOK: 'Follow user successful',
  followED: 'Already following this user',
  NotFollow: "Haven't followed this person yet",
  unfollowOK: 'Unfollow success',
  loginGoogle: 'Login with Google success',
  uploadFile: 'Upload file successful',
  refreshTokensOK: 'Refresh token successfully!',
  createTweet: 'Create tweet successfully!!',
  createBookMark: 'Tweet has saved!!',
  getTweetOk: 'Get tweet successfully!',
  getNewFeed: 'Get tweet new feed successful',
  searchTweet: (num: number): string => `Found ${num} results matched`,
  getPrivateConversation: 'Get the private conversation successful!!',
  deleteMessage: 'Delete message successfully!',
  updateMessage: 'Update private message successful'
} as const
